<?php
/**
 * EasyPopulate Language Defintions
 *
 * @package easypopulate
 * @author langer
 * @author John William Robeson, Jr <johnny@localmomentum.net>
 * @copyright 2005-2010
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License (v2 only)
 */

define('EASYPOPULATE_CONFIG_DEBUG_LOGGING_DESC', 'Log Errors  (efault: true)');
define('EASYPOPULATE_CONFIG_DEBUG_LOGGING_TITLE', 'Log Errors');
define('EASYPOPULATE_CONFIG_LOG_QUERIES_DESC', 'Log all SQL queries - useful for debugging (default: false)');
define('EASYPOPULATE_CONFIG_LOG_QUERIES_TITLE', 'Log All Queries');
define('EASYPOPULATE_CONFIG_TEMP_DIR_DESC', 'Name of directory for your uploads');
define('EASYPOPULATE_CONFIG_TEMP_DIR_TITLE', 'Uploads Directory');
define('EASYPOPULATE_CONFIG_TIME_LIMIT_DESC', '(In Seconds) You can change this if your script is taking too long to process. This functionality may be not always be enabled by your server administrator (Default: 1200)');
define('EASYPOPULATE_CONFIG_TIME_LIMIT_TITLE', 'File Processing Time Limit');
define('EASYPOPULATE_CONFIG_VERSION_DESC', 'Easy Populate version. DO NOT TOUCH!!!');
define('EASYPOPULATE_CONFIG_VERSION_TITLE', 'Easy Populate Version');

//define('EASYPOPULATE_CONFIG_IMPORT_HANDLER_TITLE', 'Default Upload File Format');
//define('EASYPOPULATE_CONFIG_IMPORT_HANDLER_DESC', 'Import File Handler');

// @todo <johnny> fix this path once it is somewhere near final
define('EASYPOPULATE_CONFIG_ADVANCED_SMART_TAGS_DESC', 'Allow the use of complex regular expressions to format descriptions, making headings bold, add bullets, etc. Configuration is in \'admin/includes/extra_datafiles/easypopulate_config.php\' (default: false)');
define('EASYPOPULATE_CONFIG_ADVANCED_SMART_TAGS_TITLE', 'Advanced Smart Tags');
define('EASYPOPULATE_CONFIG_COLUMN_DELIMITER_DESC', 'Single character used to separate column values');
define('EASYPOPULATE_CONFIG_COLUMN_DELIMITER_TITLE', 'Column Delimiter');
define('EASYPOPULATE_CONFIG_COLUMN_ENCLOSURE_DESC', 'Single character used to enclose column values');
define('EASYPOPULATE_CONFIG_COLUMN_ENCLOSURE_TITLE', 'Column Enclosure');
define('EASYPOPULATE_CONFIG_CUSTOM_FIELDS_DESC', 'Enter a comma separated list of fields to be automatically added to import/export file(ie: products_length, products_width). Please make sure field exists in PRODUCTS table');
define('EASYPOPULATE_CONFIG_CUSTOM_FIELDS_TITLE', 'Custom Products Fields');
define('EASYPOPULATE_CONFIG_DEACTIVATE_ON_ZERO_QTY_DESC', 'Mark products with a quantity of 0 inactive');
define('EASYPOPULATE_CONFIG_DEACTIVATE_ON_ZERO_QTY_TITLE', 'Mark Zero Quantity Products Inactive');
define('EASYPOPULATE_CONFIG_DEFAULT_RAW_TIME_DESC', 'If no time value stipulated in upload file, use this value. Useful for ensuring specials begin after a specific time of the day (default: 09:00:00)');
define('EASYPOPULATE_CONFIG_DEFAULT_RAW_TIME_TITLE', 'Default Raw Time');
define('EASYPOPULATE_CONFIG_DETECT_LINE_ENDIGS_DESC', 'Detect whether lines end with Mac/DOS/Unix line endings. See the <a target="_blank" href="http://php.net/manual/filesystem.configuration.php#ini.auto-detect-line-endings">PHP Manual</a> for more details(Default: true)');
define('EASYPOPULATE_CONFIG_DETECT_LINE_ENDINGS_TITLE', 'Detect Line Endings');
define('EASYPOPULATE_CONFIG_FEED_FETCH_DESC','Fetch a file containing a list of products');
define('EASYPOPULATE_CONFIG_FEED_FETCH_TITLE','Download Product Feeds');
define('EASYPOPULATE_CONFIG_FEED_SEND_EMAIL_DESC', 'Send an email containing the results of the transaction');
define('EASYPOPULATE_CONFIG_FEED_SEND_EMAIL_TITLE', 'Email Results?');
define('EASYPOPULATE_CONFIG_FILE_DATE_FORMAT_DESC', 'Choose order of date values that corresponds to your uploads file, usually generated by MS Excel. Raw dates in your uploads file (Eg 2005-09-26 09:00:00) are not affected, and will upload as they are.');
define('EASYPOPULATE_CONFIG_FILE_DATE_FORMAT_TITLE', 'Upload File Date Format');
define('EASYPOPULATE_CONFIG_IMAGE_CHECK_EXISTS_DESC','If the image file does not exist, use the zencart "No Picture" image');
define('EASYPOPULATE_CONFIG_IMAGE_CHECK_EXISTS_TITLE','Check If Image Exists');
define('EASYPOPULATE_CONFIG_IMAGE_PATH_PREFIX_DESC','Prefix all image paths in the file with this string');
define('EASYPOPULATE_CONFIG_IMAGE_PATH_PREFIX_TITLE','Image Path Prefix');
define('EASYPOPULATE_CONFIG_IMAGES_FETCH_DESC','Fetch images for a product feed from a remote location');
define('EASYPOPULATE_CONFIG_IMAGES_FETCH_TITLE','Enable Feed Image Fetching');
define('EASYPOPULATE_CONFIG_IMAGES_URL_DESC', 'Image zip file URL');
define('EASYPOPULATE_CONFIG_IMAGES_URL_TITLE', 'Image zip file location');
define('EASYPOPULATE_CONFIG_LOCAL_FILE_DESC', ' Import a file from the EasyPopulate temporary file storage directory');
define('EASYPOPULATE_CONFIG_LOCAL_FILE_TITLE', 'Import From Temp Dir');
define('EASYPOPULATE_CONFIG_MAX_CATEGORY_LEVELS_DESC', 'Maximum depth of categories required for your store. Is the number of category columns in downloaded file');
define('EASYPOPULATE_CONFIG_MAX_CATEGORY_LEVELS_TITLE', 'Maximum Category Depth');
define('EASYPOPULATE_CONFIG_METATAGS_DESCRIPTION_DESC','Add this meta description to each item');
define('EASYPOPULATE_CONFIG_METATAGS_DESCRIPTION_TITLE','Meta Description Pattern');
define('EASYPOPULATE_CONFIG_METATAGS_KEYWORDS_DESC','Add these meta keywords to each item');
define('EASYPOPULATE_CONFIG_METATAGS_KEYWORDS_TITLE','Meta Keyword Patterns');
define('EASYPOPULATE_CONFIG_METATAGS_TITLE_DESC','Add this meta title to each item');
define('EASYPOPULATE_CONFIG_METATAGS_TITLE_TITLE','Meta Title Pattern');
define('EASYPOPULATE_CONFIG_PRICE_MODIFIER_DESC','Modify all prices in the file to be processed');
define('EASYPOPULATE_CONFIG_PRICE_MODIFIER_TITLE','Price Modifier (+,-,%)');
define('EASYPOPULATE_CONFIG_PRICES_INCLUDE_TAX_DESC', 'Choose to include or exclude tax, depending on how you manage prices outside of Zen Cart');
define('EASYPOPULATE_CONFIG_PRICES_INCLUDE_TAX_TITLE', 'Prices Include Tax');
define('EASYPOPULATE_CONFIG_REPLACE_NEWLINES_DESC', 'Allows your description fields in your uploads file to have carriage returns and/or new-lines converted to HTML line-breaks on uploading, thus preserving some rudimentary formatting (default: true)');
define('EASYPOPULATE_CONFIG_REPLACE_NEWLINES_TITLE', 'Replace Newlines with <br />');
define('EASYPOPULATE_CONFIG_SITE_DESC','Which Site would like to import products into');
define('EASYPOPULATE_CONFIG_SITE_TITLE','Site');
define('EASYPOPULATE_CONFIG_SPLIT_MAX_DESC', 'Default number of records for split-file uploads. Used to avoid timeouts on large uploads (default: 300)');
define('EASYPOPULATE_CONFIG_SPLIT_MAX_TITLE', 'Split File On # Records');
define('EASYPOPULATE_CONFIG_TAX_CLASS_TITLE_DESC','Add this tax class to all items');
define('EASYPOPULATE_CONFIG_TAX_CLASS_TITLE_TITLE','Tax Class');

// UI
define('EASYPOPULATE_DISPLAY_FILE_NOT_EXIST','File does not exist: %s');
define('EASYPOPULATE_DISPLAY_FILE_OPEN_FAILED','Could not open file: %s');
define('EASYPOPULATE_DISPLAY_FILE_SPEC','%s.<br /><b>File Name: %s</b><br />Size: %s');
define('EASYPOPULATE_DISPLAY_HEADING', 'Products Summary');
define('EASYPOPULATE_DISPLAY_MESSAGE', 'Message');
define('EASYPOPULATE_DISPLAY_MODEL', 'Model');
define('EASYPOPULATE_DISPLAY_NAME', 'Name');
define('EASYPOPULATE_DISPLAY_PRICE', 'Price');
define('EASYPOPULATE_DISPLAY_RESULT_CATEGORY_NAME_LONG','Category name(s) too long (max. %s)');
define('EASYPOPULATE_DISPLAY_RESULT_CATEGORY_NOT_FOUND', 'No category provided for this%s product');
define('EASYPOPULATE_DISPLAY_RESULT_DELETED','DELETED');
define('EASYPOPULATE_DISPLAY_RESULT_DELETE_NOT_FOUND','NOT FOUND');
define('EASYPOPULATE_DISPLAY_RESULT_MODEL_NAME_LONG','Model name too long');
define('EASYPOPULATE_DISPLAY_RESULT_NEW_PRODUCT', 'ADDED');
define('EASYPOPULATE_DISPLAY_RESULT_NEW_PRODUCT_FAIL', 'ADD FAILED');
define('EASYPOPULATE_DISPLAY_RESULT_NO_MODEL', 'No model field in record. This line was not imported');
define('EASYPOPULATE_DISPLAY_RESULT_SKIPPED','SKIPPED');
define('EASYPOPULATE_DISPLAY_RESULT_SQL_ERROR', 'SQL error. Check Easy Populate error log in uploads directory');
define('EASYPOPULATE_DISPLAY_RESULT_UPDATE_PRODUCT_FAIL', 'UPDATE FAILED');
define('EASYPOPULATE_DISPLAY_RESULT_UPDATE_PRODUCT', 'UPDATED');
define('EASYPOPULATE_DISPLAY_RESULT_UPLOAD_COMPLETE', 'Upload Complete');
define('EASYPOPULATE_DISPLAY_SPLIT_LOCATION','You can also download your split files from your %s directory');
define('EASYPOPULATE_DISPLAY_STATUS', 'Status');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_CANT_WRITE, 'Failed to write file to disk');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_EXTENSION, 'File upload stopped by extension');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_FORM_SIZE, 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_INI_SIZE, 'The uploaded file exceeds the upload_max_filesize directive in php.ini');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_NO_FILE, 'No file was uploaded');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_NO_TMP_DIR, 'System (not EasyPopulate) temp directory was not found');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_OK, 'The file was successfully uploaded');
define('EASYPOPULATE_UPLOAD_ERROR_CODE_' . UPLOAD_ERR_PARTIAL, 'The file was not completely uploaded');

define('EASYPOPULATE_ERROR_NOT_INSTALLED','Easy Populate Configuration Missing. Click Install EasyPopulate');

/**
* $messageStack defines
*/
// checks - msg stack alerts - output via $messageStack
define('EASYPOPULATE_MSGSTACK_TEMP_FOLDER_MISSING','<b>Easy Populate uploads folder not found!</b><br />NIX SERVERS: Your uploads folder is either missing, or you have altered the name and/or directory of your uploads folder without configuring this in Easy Populate.<br />WINDOWS SERVERS: Please request your web host to assign write permissions to the uploads folder. This is usually granted through Windows server user account IUSR_COMPUTERNAME.<br />Your configuration indicates that your uploads folder is named <b>%s</b>, and is located in <b>%s</b>, however this cannot be found.<br />Easy Populate cannot upload files until you have provided an uploads folder with read/write/execute permissions for the site owner (usually chmod 700 but you may require chmod 777)');
define('EASYPOPULATE_MSGSTACK_ERROR_SQL', 'An SQL error has occured. Please check your input data for tabs within fields and delete these. If this error continues, please forward your error log to the Easy Populate maintainer');
define('EASYPOPULATE_MSGSTACK_DROSS_DELETE_FAIL', '<b>Deleting of product data debris failed!</b> Please see the debug log in your uploads directory for further information.');
define('EASYPOPULATE_MSGSTACK_DROSS_DELETE_SUCCESS', 'Deleting of product data debris succeeded!');
define('EASYPOPULATE_MSGSTACK_DROSS_DETECTED', '<b>%s partially deleted product(s) found!</b> Delete this dross to prevent unwanted zencart behaviour by clicking <a href="%s">here.</a><br />You are seeing this because there are references in tables to a product that no longer exists, which is usually caused by an incomplete product deletion. This can cause Zen Cart to misbehave in certain circumstances.');
define('EASYPOPULATE_MSGSTACK_DATE_FORMAT_FAIL', '%s is not a valid date format. If you upload any date other than raw format (such as from Excel) you will mangle your dates. Please fix this by correcting your date format in the Easy Populate config.');
define('EASYPOPULATE_MSGSTACK_INSTALL_SUCCESS','<b>Installation Successfull!</b>  A full download of your store has been done and is available in your uploads (tempEP) directory. You can use this as your 1st template for uploading/updating products.');

// file handling - msg stack alerts - output via $messageStack
define('EASYPOPULATE_MSGSTACK_FILE_EXPORT_SUCCESS', 'File <b>%s</b> successfully exported! The file is ready for download in your /%s directory.');

// html template - bottom of admin/easypopulate.php
// langer - will add after html renovation

/**
* $printsplit defines
*/
// splitting files results text - in $printsplit
define('EASYPOPULATE_FILE_SPLITS_HEADING', 'Upload split files in turn');
define('EASYPOPULATE_FILE_SPLIT_COMPLETED', 'Upload done of ');
define('EASYPOPULATE_FILE_SPLITS_DONE', 'All done!');
define('EASYPOPULATE_FILE_SPLIT_PENDING', 'Pending Upload of ');
define('EASYPOPULATE_FILE_SPLIT_ANCHOR_TEXT', 'Upload ');
// misc
define('EASYPOPULATE_FILE_SPLITS_PREFIX', 'Split-');

// Specials results
define('EASYPOPULATE_SPECIALS_HEADING', 'Specials Summary');
define('EASYPOPULATE_SPECIALS_PRICE', 'Specials Price');
define('EASYPOPULATE_SPECIALS_PRICE_FAIL', 'Specials price higher than normal price');
define('EASYPOPULATE_SPECIALS_DELETE_FAIL', 'Can\t delete special');

// error log defines - for ep_debug_log.txt
//define('EASYPOPULATE_ERRORLOG_SQL_ERROR', 'MySQL error %s: %s\nWhen executing:\n%sn');
?>
